pipeline:
  name: nodejsjspipelines
  identifier: nodejsjspipelines
  projectIdentifier: nodejspipeline
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: git_new
        repoName: harness-nodejs
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: BuildAndPush
        identifier: BuildAndPush
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: gkeconnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build_Docker_Image
                  identifier: Build_Docker_Image
                  spec:
                    connectorRef: GCP_Connector
                    repo: gcr.io/just-skyline-458709-a8/harness-nodejs
                    tags:
                      - latest
                  resources:
                    limits:
                      memory: 300Mi
                      cpu: 200m
                    requests:
                      memory: 150Mi
                      cpu: 100m
              - step:
                  type: Run
                  name: Run_Unit_Tests
                  identifier: Run_Unit_Tests
                  spec:
                    image: node:18
                    connectorRef: gkeconnector
                    shell: Sh
                    command: |
                      echo "Installing dependencies..."
                      npm install
                      echo "Running unit tests..."
                      npm test
                  resources:
                    limits:
                      memory: 300Mi
                      cpu: 200m
                    requests:
                      memory: 150Mi
                      cpu: 100m
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
